fix: adds missing Link from Gatsby on 404 page (#18)
Build fails without this

```
Building static HTML failed for path "/404/"
...
  WebpackError: ReferenceError: Link is not defined
```
fixes #15